export const capabilities = [
  {
    id: "sources",
    group: "数据接入",
    name: "数据源",
    description: "版本化连接、真实测试与元数据变化",
    stage: "M4a",
    features: ["合成CSV连接管理", "真实文件连接测试", "字段类型与结构变化"],
  },
  {
    id: "sync",
    group: "数据接入",
    name: "数据同步",
    description: "离线全量/增量落地与后续实时同步",
    stage: "M4b",
    features: [
      "FULL与INCREMENTAL_UPSERT",
      "字段映射、主键与水位",
      "本机事件流、Checkpoint与断点恢复",
      "Kafka/Flink生产适配（后续）",
    ],
  },
  {
    id: "development",
    group: "开发交付",
    name: "数据开发",
    description: "SQL 编写、运行与结果核验",
    stage: "M1",
    features: ["代码编辑与版本", "真实 Spark SQL", "独立结果断言"],
  },
  {
    id: "schedules",
    group: "开发交付",
    name: "调度与发布",
    description: "已验证 SQL 的交付、审批、定时发布与监控",
    stage: "M2c",
    features: [
      "版本化调度与部署文件",
      "样例交易日历与DAG校验",
      "本机文件演练",
      "摘要审批与本机计时发布",
      "批次监控、告警恢复与回滚",
    ],
  },
  {
    id: "assets",
    group: "治理与服务",
    name: "数据资产",
    description: "可搜索目录、版本血缘、指标与标准",
    stage: "M4c",
    features: [
      "真实资源自动入目录",
      "版本绑定与字段映射血缘",
      "实际行指标与数据标准",
      "Data Agent受治理发现与影响解释",
    ],
  },
  {
    id: "quality",
    group: "治理与服务",
    name: "数据质量",
    description: "规则、实际检测与异常处理",
    stage: "M4",
    features: ["规则配置", "真实检查", "告警关联"],
  },
  {
    id: "security",
    group: "治理与服务",
    name: "安全与脱敏",
    description: "权限、脱敏与访问审计",
    stage: "M4",
    features: ["身份与行列策略", "脱敏规则", "权限申请与审计"],
  },
  {
    id: "services",
    group: "治理与服务",
    name: "数据服务",
    description: "开发、测试、发布和治理 DAPI/XAPI",
    stage: "M3",
    features: [
      "真实发布结果的参数化DAPI",
      "固定子版本的声明式XAPI",
      "授权、限流、超时、OpenAPI与调用日志",
      "Data Agent受治理方案",
    ],
  },
  {
    id: "reports",
    group: "治理与服务",
    name: "数据报表",
    description: "指标、数据集与业务洞察",
    stage: "M4",
    features: ["实际加工结果", "可视化与导出", "语义问数"],
  },
  {
    id: "ops",
    group: "运行管理",
    name: "运维监控",
    description: "日志、告警与运行状态",
    stage: "M4",
    features: ["执行批次与日志", "运行证据", "告警与恢复"],
  },
  {
    id: "settings",
    group: "运行管理",
    name: "平台设置",
    description: "运行环境与模型接入",
    stage: "M0",
    features: ["模型配置状态", "引擎就绪检查", "预算与部署前置条件"],
  },
];
