export const capabilities = [
  {
    id: "sources",
    group: "数据接入",
    name: "数据源",
    description: "连接配置、测试与凭证引用",
    stage: "M4",
    features: ["连接管理", "真实连接测试", "表结构采集"],
  },
  {
    id: "sync",
    group: "数据接入",
    name: "数据同步",
    description: "离线与实时数据同步",
    stage: "M4",
    features: ["全量与增量", "字段映射", "CDC 与恢复"],
  },
  {
    id: "development",
    group: "开发交付",
    name: "数据开发",
    description: "SQL 编写、运行与结果核验",
    stage: "M1",
    features: ["代码编辑与版本", "真实 Spark SQL", "独立结果断言"],
  },
  {
    id: "schedules",
    group: "开发交付",
    name: "调度与发布",
    description: "工作流、依赖与版本交付",
    stage: "M2",
    features: ["DAG 与交易日历", "部署文件", "灰度与回滚"],
  },
  {
    id: "assets",
    group: "治理与服务",
    name: "数据资产",
    description: "目录、元数据与血缘",
    stage: "M4",
    features: ["字段说明", "指标与标准", "血缘和契约"],
  },
  {
    id: "quality",
    group: "治理与服务",
    name: "数据质量",
    description: "规则、实际检测与异常处理",
    stage: "M4",
    features: ["规则配置", "真实检查", "告警关联"],
  },
  {
    id: "security",
    group: "治理与服务",
    name: "安全与脱敏",
    description: "权限、脱敏与访问审计",
    stage: "M4",
    features: ["身份与行列策略", "脱敏规则", "权限申请与审计"],
  },
  {
    id: "services",
    group: "治理与服务",
    name: "数据服务",
    description: "开发发布 DAPI 与 XAPI",
    stage: "M3",
    features: ["参数化查询 DAPI", "组合编排 XAPI", "授权、版本与调用监控"],
  },
  {
    id: "reports",
    group: "治理与服务",
    name: "数据报表",
    description: "指标、数据集与业务洞察",
    stage: "M4",
    features: ["实际加工结果", "可视化与导出", "语义问数"],
  },
  {
    id: "ops",
    group: "运行管理",
    name: "运维监控",
    description: "日志、告警与运行状态",
    stage: "M4",
    features: ["执行批次与日志", "运行证据", "告警与恢复"],
  },
  {
    id: "settings",
    group: "运行管理",
    name: "平台设置",
    description: "运行环境与模型接入",
    stage: "M0",
    features: ["模型配置状态", "引擎就绪检查", "预算与部署前置条件"],
  },
];
